[package]
name = "orm"
version = "0.1.0"
description = "ORM for OpenCTF, based on diesel.rs"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[features]
default = ["mysql"]
mysql = ["r2d2_mysql"]

[dependencies]
r2d2 = "0.8"
url = "1.7"

r2d2_mysql = { version = "9.0", optional = true }
